const PRINT_NUMBER = "PRINT_NUMBER";
const CLEAR_CALCUL = "CLEAR_CALCUL";
const ADD = "ADD";
const SUBTRACT = "SUBTRACT";
const DIVIDE = "DIVIDE";
const MULT = "MULT";
const EQUAL = "EQUAL";
const ADD_DOT = "ADD_DOT";
export { PRINT_NUMBER, CLEAR_CALCUL,ADD,SUBTRACT,DIVIDE,MULT,EQUAL,ADD_DOT };
